-- Seed interests data from the application
-- This migration populates the interests table with all available interests

INSERT INTO interests (id, name, emoji, category) VALUES
-- Science, Technology & Professional Interests
('ai-robotics', 'AI & Robotics', '🤖', 'Science, Technology & Professional Interests'),
('it-software', 'IT & Software Development', '👨‍💻', 'Science, Technology & Professional Interests'),
('hardware-dev', 'Hardware Development', '📱', 'Science, Technology & Professional Interests'),
('vr-ar', 'Virtual & Augmented Reality', '🥽', 'Science, Technology & Professional Interests'),
('psychology', 'Psychology', '🧠', 'Science, Technology & Professional Interests'),
('philosophy', 'Philosophy', '🤔', 'Science, Technology & Professional Interests'),
('astronomy', 'Astronomy', '🔭', 'Science, Technology & Professional Interests'),
('math', 'Math', '🧮', 'Science, Technology & Professional Interests'),
('physics', 'Physics', '👨‍🏫', 'Science, Technology & Professional Interests'),
('biology', 'Biology', '🧬', 'Science, Technology & Professional Interests'),
('chemistry', 'Chemistry', '🧪', 'Science, Technology & Professional Interests'),
('languages', 'Languages', '👅', 'Science, Technology & Professional Interests'),
('engineering', 'Engineering', '💡', 'Science, Technology & Professional Interests'),
('law', 'Law', '🧑‍⚖️', 'Science, Technology & Professional Interests'),
('ecology', 'Ecology & Circular Economy', '♻️', 'Science, Technology & Professional Interests'),
('religion', 'Religion', '🙏', 'Science, Technology & Professional Interests'),
('design', 'Design', '⚜️', 'Science, Technology & Professional Interests'),
('finance', 'Finance & Investment', '💵', 'Science, Technology & Professional Interests'),
('crypto', 'Crypto & WEB 3.0', '🔐', 'Science, Technology & Professional Interests'),
('business', 'Business studies', '👨‍💼', 'Science, Technology & Professional Interests'),
('entrepreneurship', 'Entrepreneurship', '🦄', 'Science, Technology & Professional Interests'),
('statistics', 'Statistics & Data Analytics', '📊', 'Science, Technology & Professional Interests'),
('media-film', 'Media and Filmmaking', '📺', 'Science, Technology & Professional Interests'),
('music-prof', 'Music', '🎶', 'Science, Technology & Professional Interests'),
('politics', 'Government & Politics', '🏛️', 'Science, Technology & Professional Interests'),
('security', 'Security & Defense', '👮', 'Science, Technology & Professional Interests'),

-- Free Time Activities
('traveling', 'Traveling', '✈️', 'Free Time Activities'),
('sightseeing', 'Sightseeing & city exploring', '🗽', 'Free Time Activities'),
('nature', 'Nature exploring', '🌳', 'Free Time Activities'),
('reading', 'Reading', '📖', 'Free Time Activities'),
('music', 'Music', '🎧', 'Free Time Activities'),
('partying', 'Partying', '🎉', 'Free Time Activities'),
('painting', 'Painting', '🎨', 'Free Time Activities'),
('cooking', 'Cooking', '👨‍🍳', 'Free Time Activities'),
('cars', 'Cars', '🚗', 'Free Time Activities'),
('motorcycles', 'Motorcycles', '🏍️', 'Free Time Activities'),
('podcasts', 'Youtube & Podcasts', '💬', 'Free Time Activities'),
('singing', 'Singing', '🎤', 'Free Time Activities'),
('writing', 'Writing', '✍️', 'Free Time Activities'),
('self-care', 'Self-care & Longevity', '💆‍♀️', 'Free Time Activities'),
('art', 'Art', '🎨', 'Free Time Activities'),
('fishing', 'Fishing', '🎣', 'Free Time Activities'),
('hunting', 'Hunting', '🐗', 'Free Time Activities'),
('darts', 'Darts', '🎯', 'Free Time Activities'),
('billiard', 'Billiard', '🎱', 'Free Time Activities'),
('bowling', 'Bowling', '🎳', 'Free Time Activities'),
('dancing', 'Dancing', '💃', 'Free Time Activities'),
('gaming', 'Gaming', '🎮', 'Free Time Activities'),
('puzzle', 'Puzzle & Escape rooms', '🧩', 'Free Time Activities'),
('card-games', 'Card games', '♠️', 'Free Time Activities'),
('events', 'Events & Networking', '🎟️', 'Free Time Activities'),
('drinks', 'Drinks with friends', '🍻', 'Free Time Activities'),
('dating', 'Dating', '👫', 'Free Time Activities'),
('restaurants', 'Restaurants', '🍽️', 'Free Time Activities'),
('shopping', 'Shopping', '🛍️', 'Free Time Activities'),
('chess', 'Chess', '♟️', 'Free Time Activities'),
('picnic', 'Picnic', '🧺', 'Free Time Activities'),
('beach', 'Beach', '🏖️', 'Free Time Activities'),
('walking', 'Walking', '🚶', 'Free Time Activities'),
('dog-walking', 'Dog walking', '🐕', 'Free Time Activities'),

-- Outdoor Activities
('hiking', 'Hiking', '🥾', 'Outdoor Activities'),
('camping', 'Camping', '🏕️', 'Outdoor Activities'),
('climbing', 'Climbing', '🧗', 'Outdoor Activities'),
('motocross', 'Motocycle/Motorcross', '🏍️', 'Outdoor Activities'),
('mountain-biking', 'Mountain biking', '🚵', 'Outdoor Activities'),
('scuba-diving', 'Scuba diving', '🤿', 'Outdoor Activities'),
('kite-surfing', 'Kite surfing', '🪁', 'Outdoor Activities'),
('windsurfing', 'Windsurfing', '🏄', 'Outdoor Activities'),
('rafting', 'Rafting', '🛶', 'Outdoor Activities'),
('skydiving', 'Skydiving', '🪂', 'Outdoor Activities'),
('bungee-jumping', 'Bungee jumping', '🪢', 'Outdoor Activities'),
('paintball', 'Paintball / Airsoft', '🔫', 'Outdoor Activities'),
('skateboarding', 'Skateboarding', '🛹', 'Outdoor Activities'),
('jet-skiing', 'Jet skiing', '🚤', 'Outdoor Activities'),
('paragliding', 'Paragliding', '🪂', 'Outdoor Activities'),
('racing', 'Racing/Karting', '🏎️', 'Outdoor Activities'),
('snorkeling', 'Snorkeling', '🤿', 'Outdoor Activities'),
('sailing', 'Sailing', '⛵️', 'Outdoor Activities'),

-- Sports
('running', 'Running', '🏃', 'Sports'),
('cycling', 'Cycling', '🚴', 'Sports'),
('swimming', 'Swimming', '🏊', 'Sports'),
('fitness', 'Fitness / bodybuilding', '💪', 'Sports'),
('boxing', 'Boxing', '🥊', 'Sports'),
('lifting', 'Lifting', '🏋️', 'Sports'),
('football', 'Football', '⚽️', 'Sports'),
('basketball', 'Basketball', '🏀', 'Sports'),
('volleyball', 'Volleyball', '🏐', 'Sports'),
('baseball', 'Baseball', '⚾️', 'Sports'),
('tennis', 'Tennis', '🎾', 'Sports'),
('hockey', 'Hockey', '🏑', 'Sports'),
('squash', 'Squash', '⚫️', 'Sports'),
('golf', 'Golf', '⛳️', 'Sports'),
('rugby', 'Rugby', '🏉', 'Sports'),
('badminton', 'Badminton', '🏸', 'Sports'),
('table-tennis', 'Table tennis', '🏓', 'Sports'),
('padel', 'Padel', '🎾', 'Sports'),
('skiing', 'Skiing', '🎿', 'Sports'),
('snowboarding', 'Snowboarding', '🏂', 'Sports'),
('martial-arts', 'Martial arts', '🥋', 'Sports'),
('stretching', 'Stretching', '🧘', 'Sports'),
('pilates', 'Pilates', '🧘‍♀️', 'Sports'),
('calisthenics', 'Calisthenics', '🤸', 'Sports'),
('kayaking', 'Kayaking', '🛶', 'Sports'),
('gymnastics', 'Gymnastics', '🤸‍♀️', 'Sports'),
('handball', 'Handball', '🤾', 'Sports'),
('yoga', 'Yoga', '🧘‍♂️', 'Sports'),

-- Entertainment interests
('cinema', 'Cinema', '🍿', 'Entertainment interests'),
('theatre', 'Theatre', '🎭', 'Entertainment interests'),
('bars-clubs', 'Bars & Clubs', '🪩', 'Entertainment interests'),
('concerts', 'Concerts', '🎶', 'Entertainment interests'),
('festivals', 'Festivals', '🎉', 'Entertainment interests'),
('stand-up', 'Stand up shows', '🎙️', 'Entertainment interests'),
('karaoke', 'Karaoke', '🎤', 'Entertainment interests'),
('museums', 'Museums & galleries', '🏛️', 'Entertainment interests'),
('acting', 'Acting', '🎬', 'Entertainment interests'),
('fashion', 'Fashion', '👗', 'Entertainment interests'),
('movies-series', 'Movies & series', '📺', 'Entertainment interests'),
('arts', 'Arts', '🖼️', 'Entertainment interests'),
('gaming-ent', 'Gaming', '🎮', 'Entertainment interests'),

-- Hobbies & Abstract interests
('magic', 'Magic', '🔮', 'Hobbies & Abstract interests'),
('secret-societies', 'Secret societies', '🥷', 'Hobbies & Abstract interests'),
('conspiracies', 'Conspiracies', '👁️', 'Hobbies & Abstract interests'),
('tarot', 'Tarot', '🃏', 'Hobbies & Abstract interests'),
('detective', 'Detective / Thriller stories', '🕵️‍♂️', 'Hobbies & Abstract interests'),
('paranormal', 'Ghosts / Paranormal activities', '👻', 'Hobbies & Abstract interests'),
('ufos', 'UFOs', '🛸', 'Hobbies & Abstract interests'),
('sci-fi', 'Sci-fi', '👨‍🚀', 'Hobbies & Abstract interests'),
('interstellar', 'Interstellar Sagas (Star Wars, Dune, Star Trek, etc.)', '👽', 'Hobbies & Abstract interests'),
('anime', 'Anime', '🐱', 'Hobbies & Abstract interests'),
('fantasy', 'Fantasy', '🧝', 'Hobbies & Abstract interests'),
('astrology', 'Astrology', '♏', 'Hobbies & Abstract interests'),
('archeology', 'Archeology', '🏺', 'Hobbies & Abstract interests'),
('history', 'History', '📜', 'Hobbies & Abstract interests'),
('board-games', 'Board games', '🎲', 'Hobbies & Abstract interests'),
('meditation', 'Meditation', '🧘', 'Hobbies & Abstract interests'),
('aviation', 'Aviation', '✈️', 'Hobbies & Abstract interests'),
('military', 'Military', '🪖', 'Hobbies & Abstract interests'),
('gambling', 'Gambling', '🎰', 'Hobbies & Abstract interests'),
('comics', 'Comics', '🦹‍♀️', 'Hobbies & Abstract interests'),
('collecting', 'Collecting (Stamps, Watches, Books, etc.)', '📚', 'Hobbies & Abstract interests'),
('hermetic', 'Hermetic studies', '🪬', 'Hobbies & Abstract interests'),
('religion-abstract', 'Religion', '🙏', 'Hobbies & Abstract interests'),
('interdimensional', 'Interdimensional experiences', '🧚‍♀️', 'Hobbies & Abstract interests')

ON CONFLICT (id) DO NOTHING;

